import { useState } from "react"
import DashboardLayout from "../layouts/DashboardLayout.jsx"
import { api, readableError } from "../services/api"
import { useApiQuery } from "../hooks/useApiQuery"
import { ErrorState, LoadingState } from "../components/AsyncState"

function DoctorEmergency() {
  const { data: patients, loading, error, refresh } = useApiQuery(api.doctorPatients, [])
  const [patientId, setPatientId] = useState(""); const [reason, setReason] = useState(""); const [active, setActive] = useState(null); const [summary, setSummary] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [query, setQuery] = useState(""); const [ragResult, setRagResult] = useState(null); const [integrity, setIntegrity] = useState(null)
  async function start() { if (!patientId || reason.trim().length < 5) return setMessage("Select a patient and provide an emergency reason."); setBusy(true); setMessage(""); try { const result = await api.breakGlass({ patient_id: patientId, reason: reason.trim() }); setActive(result); setSummary(await api.emergencySummary(patientId)) } catch (requestError) { setMessage(readableError(requestError)) } finally { setBusy(false) } }
  async function end() { setBusy(true); try { await api.endBreakGlass({ patient_id: patientId, reason: "Emergency treatment concluded" }); setActive(null); setSummary(null); setMessage("Emergency session ended.") } catch (requestError) { setMessage(readableError(requestError)) } finally { setBusy(false) } }
  async function searchHistory(event) { event.preventDefault(); if (!query.trim()) return; setBusy(true); try { setRagResult(await api.ragQuery({ patient_id: patientId, question: query.trim(), max_sources: 5 })) } catch (requestError) { setMessage(readableError(requestError)) } finally { setBusy(false) } }
  async function verify(eventId) { if (!eventId) return setMessage("This summary has no integrity event ID."); setBusy(true); try { setIntegrity(await api.verifyIntegrity(eventId)) } catch (requestError) { setMessage(readableError(requestError)) } finally { setBusy(false) } }
  return <DashboardLayout role="doctor" userName="Doctor"><div className="doctor-page polished-emergency-page"><div className="dashboard-page-header"><div><div className="page-eyebrow">EMERGENCY ACCESS</div><h1>Break-glass passport</h1><p>Temporary emergency access is read-only and visible to the patient through audit logs.</p></div></div>{loading && <LoadingState label="Loading accessible patients…" />}{error && <ErrorState error={error} onRetry={refresh} />}{message && <div className="document-message" role="alert">{message}</div>}{!loading && !error && !active && <section className="dashboard-panel"><div className="section-kicker">START SESSION</div><h2>Request emergency access</h2><select value={patientId} onChange={(event) => setPatientId(event.target.value)}><option value="">Select patient</option>{(patients || []).map((item) => <option key={item.patient_id || item.id} value={item.patient_id || item.id}>{item.full_name || item.name || item.patient_id}</option>)}</select><textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason for emergency access" rows="4" /><button className="primary-action-button" type="button" disabled={busy} onClick={start}>{busy ? "Starting…" : "Start read-only access"}</button></section>}{active && <><div className="emergency-session-strip"><strong>Emergency session active — READ ONLY</strong><span>Expires {active.expires_at ? new Date(active.expires_at).toLocaleString() : "per backend policy"}</span><button className="secondary-action-button" type="button" onClick={end} disabled={busy}>End session</button></div><section className="dashboard-panel"><div className="section-kicker">EMERGENCY SUMMARY</div><h2>{summary?.profile?.full_name || summary?.patient?.full_name || patientId}</h2><p>Reason: {active.reason || reason}</p><pre className="clinical-output">{JSON.stringify(summary || {}, null, 2)}</pre><p className="readonly-badge">Read-only: upload, OCR, approval, access grants, and record edits are unavailable.</p><button type="button" className="secondary-action-button" onClick={() => verify(summary?.critical_events?.[0]?.event_id || summary?.medical_events?.[0]?.event_id)}>Verify integrity</button>{integrity && <pre className="clinical-output">{JSON.stringify(integrity, null, 2)}</pre>}</section><section className="dashboard-panel"><div className="section-kicker">HISTORICAL RAG</div><h2>Read-only historical query</h2><form onSubmit={searchHistory}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ask about the patient's history" /><button className="secondary-action-button" type="submit" disabled={busy}>Search history</button></form>{ragResult && <pre className="clinical-output">{JSON.stringify(ragResult, null, 2)}</pre>}</section></>}</div></DashboardLayout>
}
export default DoctorEmergency
