import { useState } from "react"
import DashboardLayout from "../layouts/DashboardLayout.jsx"
import { api } from "../services/api"
import { useApiQuery } from "../hooks/useApiQuery"
import { ErrorState, LoadingState } from "../components/AsyncState"

function DoctorIntegrity() {
  const [patientId, setPatientId] = useState(""); const [result, setResult] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false)
  const directory = useApiQuery(api.doctorPatients, []); const summary = useApiQuery(() => patientId ? api.patientSummary(patientId) : Promise.resolve(null), [patientId]); const events = summary.data?.medical_events || []
  async function verify(eventId) { setBusy(true); setMessage(""); try { setResult(await api.verifyIntegrity(eventId)) } catch (requestError) { setMessage(requestError.status === 403 ? "You do not have permission to verify this event." : requestError.message) } finally { setBusy(false) } }
  return <DashboardLayout role="doctor" userName="Doctor"><div className="doctor-page"><div className="dashboard-page-header"><div><div className="page-eyebrow">INTEGRITY</div><h1>Event provenance</h1><p>Integrity verification reports provenance status, not clinical truth.</p></div></div>{directory.loading && <LoadingState label="Loading accessible patients…" />}{directory.error && <ErrorState error={directory.error} onRetry={directory.refresh} />}{!directory.loading && !directory.error && <section className="dashboard-panel"><h2>Select patient</h2><select value={patientId} onChange={(event) => { setPatientId(event.target.value); setResult(null) }}><option value="">Select patient</option>{(directory.data || []).map((item) => <option key={item.patient_id || item.id} value={item.patient_id || item.id}>{item.full_name || item.name || item.patient_id}</option>)}</select></section>}{patientId && summary.loading && <LoadingState label="Loading critical events…" />}{patientId && summary.error && <ErrorState error={summary.error} onRetry={summary.refresh} />}{patientId && !summary.loading && !summary.error && <section className="dashboard-panel"><div className="section-kicker">CRITICAL MEDICAL EVENTS</div>{events.length ? events.map((event, index) => <article className="audit-row" key={event.event_id || event.id || index}><strong>{event.title || event.event_type || "Medical event"}</strong><p>{event.description || "No description returned."}</p><button className="secondary-action-button" type="button" disabled={busy} onClick={() => verify(event.event_id || event.id)}>Verify integrity</button></article>) : <p>No events returned for this patient.</p>}{result && <pre className="clinical-output">{JSON.stringify(result, null, 2)}</pre>}</section>}{message && <div className="document-message" role="alert">{message}</div>}</div></DashboardLayout>
}
export default DoctorIntegrity
