import { useState } from "react"
import DashboardLayout from "../layouts/DashboardLayout.jsx"
import { api, readableError, session } from "../services/api"
import { useApiQuery } from "../hooks/useApiQuery"
import { ErrorState, LoadingState } from "../components/AsyncState"

function PatientAccess() {
  const { data, loading, error, refresh } = useApiQuery(api.patientMe, [])
  const [doctor, setDoctor] = useState(""); const [duration, setDuration] = useState("7"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false)
  const patientId = data?.patient_id || data?.profile?.patient_id || data?.profile?.id || session.get()?.user?.patient_id
  const access = data?.accesses || data?.access_grants || data?.doctors || []
  async function grant(event) { event.preventDefault(); if (!doctor.trim()) return setMessage("Enter a doctor ID or email."); setBusy(true); setMessage(""); const payload = doctor.includes("@") ? { doctor_email: doctor.trim(), duration_days: Number(duration) } : { doctor_id: doctor.trim(), duration_days: Number(duration) }; try { await api.grantAccess(patientId, payload); setMessage("Doctor access granted."); setDoctor(""); refresh() } catch (requestError) { setMessage(readableError(requestError)) } finally { setBusy(false) } }
  async function revoke(item) { if (!window.confirm(`Revoke access for ${item.doctor_name || item.full_name || "this doctor"}?`)) return; setBusy(true); try { await api.revokeAccess(patientId, item.access_id || item.id); setMessage("Doctor access revoked."); refresh() } catch (requestError) { setMessage(readableError(requestError)) } finally { setBusy(false) } }
  return <DashboardLayout role="patient" userName={data?.profile?.full_name || "Patient"}><div className="patient-access-page"><div className="dashboard-page-header"><div><div className="page-eyebrow">PRIVACY & ACCESS</div><h1>Doctor Access Control</h1><p>Grant temporary normal access or revoke it immediately. The backend remains authoritative.</p></div></div>{message && <div className="access-action-message" role="status">{message}</div>}{loading && <LoadingState label="Loading access settings…" />}{error && <ErrorState error={error} onRetry={refresh} />}{!loading && !error && <><section className="dashboard-panel"><div className="section-kicker">GIVE ACCESS</div><h2>Grant a doctor access</h2><form onSubmit={grant}><label>Doctor ID or email<input value={doctor} onChange={(event) => setDoctor(event.target.value)} placeholder="doctor@example.com" required /></label><label>Duration<select value={duration} onChange={(event) => setDuration(event.target.value)}><option value="1">1 day</option><option value="7">7 days</option><option value="30">30 days</option></select></label><button className="primary-action-button" type="submit" disabled={busy || !patientId}>{busy ? "Updating…" : "Grant access"}</button></form></section><section className="dashboard-panel"><div className="section-kicker">ACTIVE ACCESS</div><h2>Doctors with access</h2>{access.length === 0 ? <p>The backend did not return any access records. You can grant access above.</p> : <div className="doctor-access-list">{access.map((item) => { const active = String(item.access_status || item.status || "").toUpperCase() === "ACTIVE" || item.access === true; return <div className="doctor-access-card" key={item.access_id || item.id || item.doctor_id}><div><strong>{item.doctor_name || item.full_name || item.doctor_email || "Doctor"}</strong><p>{active ? "ACTIVE" : item.access_status || item.status || "Not active"}</p>{item.access_expiry && <small>Expires {new Date(item.access_expiry).toLocaleString()}</small>}</div>{active && <button className="revoke-button" type="button" disabled={busy} onClick={() => revoke(item)}>Revoke access</button>}</div>})}</div>}</section></>}</div></DashboardLayout>
}
export default PatientAccess
